- name: "create config folder"
  shell: "{{ item }}"
  with_items:
  - "mkdir {{ home_dir }}/cardano-node/config_files"
- name: "transferring {{ node_alias }} configs and services"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   mode: "{{item.mode}}"
  with_items:
  - { src: 'ff-config.json',dest: '{{ home_dir }}/cardano-node/config_files/config.json', mode: '0755'}
  - { src: 'ff-genesis.json',dest: '{{ home_dir }}/cardano-node/config_files/genesis.json', mode: '0755'}
  - { src: 'ff-topology.json',dest: '{{ home_dir }}/cardano-node/config_files/topology.json', mode: '0755'}
  - { src: 'cardano-node.environment',dest: '{{ home_dir }}/cardano-node/cardano-node.environment', mode: '0755'}
  - { src: 'relay_node_shelley.service',dest: '/etc/systemd/system/relay_node.service', mode: '0755'}
  - { src: 'node_exporter.service',dest: '/etc/systemd/system/node_exporter.service', mode: '0755'}
- name: "add launch alias in bashrc"
  lineinfile:
   path: ~/.bashrc
   line: "{{ item }}"
  with_items:
  - alias relaylaunch='cardano-node run --topology config_files/topology.json --database-path config_files/db --socket-path config_files/db/node.socket --host-addr 0.0.0.0 --port 7881 --config config_files/config.json'
- name: "Installing Node Exporter"
  shell: "{{ item }}"
  with_items:
  - wget https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
  - tar xvf node_exporter-0.16.0.linux-amd64.tar.gz
  - sudo cp node_exporter-0.16.0.linux-amd64/node_exporter /usr/local/bin
  - rm -rf node_exporter-0.16.0.linux-amd64.tar.gz node_exporter-0.16.0.linux-amd64
- name: "Enable ufw"
  ufw: state=enabled policy=allow
- name: "Disable default incoming"
  ufw: direction=incoming policy=deny
- name: "allow ssh in"
  ufw: rule=limit name=OpenSSH
- name: "configure | rules"
  ufw:
   rule: "{{ item.rule }}"
   interface: "{{ item.interface | default('') }}"
   direction: "{{ item.direction | default('in') }}"
   from_ip: "{{ item.from_ip | default('any') }}"
   to_ip: "{{ item.to_ip | default('any') }}"
   from_port: "{{ item.from_port | default('') }}"
   to_port: "{{ item.to_port | default('') }}"
   protocol: "{{ item.protocol | default('any') }}"
   route: "{{ item.route | default(omit) }}"
   log: "{{ item.log | default(false) }}"
   comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ ufw_rules }}"
  notify: reload ufw
- name: "Enable Logging & restart ufw"
  ufw: logging=on
  notify: reload ufw
- name: "View Ufw rules"
  command: ufw status
  register: out
- debug: var=out.stdout_lines
- name: "Install netfilter-persistent && iptables-persistent packages"
  package:
   name: "{{item}}"
   state: present
  with_items:
  - iptables-persistent
  - netfilter-persistent
  when: ansible_os_family == "Ubuntu"
- name: "save iptables"
  command: iptables-save
- name: "Install the fail2ban package"
  package:
   name: fail2ban
   state: latest
- name: "Override some basic fail2ban configurations"
  copy:
   src: jail.local  
   dest: /etc/fail2ban/jail.local
   owner: root
   group: root
   mode: 0644
- name: "Enable firewall"
  ufw: state=enabled
  notify: Restart ssh
- name: "Change ssh port to user defined"
  lineinfile: 
   dest=/etc/ssh/sshd_config
   regexp="^Port\s"
   line="Port {{ ubuntu_login_ssh_port }}"
   state=present
  notify: Restart ssh
- name: "Disallow root SSH access"
  lineinfile: 
   dest=/etc/ssh/sshd_config
   regexp="^PermitRootLogin"
   line="PermitRootLogin no"
   state=present
  notify: Restart ssh
