- name: "Installing and configuring prometheus"
  shell: "{{ item }}"
  with_items:
  - sudo mkdir /etc/prometheus
  - sudo mkdir /var/lib/prometheus
  - wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
  - tar xfz prometheus-*.tar.gz
- name: "Setting up Prometheus"
  command: "{{ item }} chdir=/root/prometheus-2.19.0.linux-amd64"
  with_items:
  - sudo cp ./prometheus /usr/local/bin/
  - sudo cp ./promtool /usr/local/bin/
  - sudo cp -r ./consoles /etc/prometheus
  - sudo cp -r ./console_libraries /etc/prometheus
- name: "Downloading Grafana"
  shell: "{{ item }}"
  with_items:
  - rm -rf /root/prometheus-*
  - wget https://dl.grafana.com/oss/release/grafana_7.0.3_amd64.deb
  - sudo apt-get install -y adduser libfontconfig
  - sudo dpkg -i grafana_7.0.3_amd64.deb
- name: "transferring {{ node_alias }} services"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   mode: "{{item.mode}}"
  with_items:
  - { src: 'prometheus.yml',dest: '/etc/prometheus/prometheus.yml', mode: '0755'}
  - { src: 'prometheus.service',dest: '/etc/systemd/system/prometheus.service', mode: '0755'}
- name: "transfer git key"
  copy:
   src: git_remote_access_key
   dest: /root/.ssh
   mode: 0640
- name: "Enable ufw"
  ufw: state=enabled policy=allow
- name: "Disable default incoming"
  ufw: direction=incoming policy=deny
- name: "allow ssh in"
  ufw: rule=limit name=OpenSSH
- name: "configure | rules"
  ufw:
   rule: "{{ item.rule }}"
   interface: "{{ item.interface | default('') }}"
   direction: "{{ item.direction | default('in') }}"
   from_ip: "{{ item.from_ip | default('any') }}"
   to_ip: "{{ item.to_ip | default('any') }}"
   from_port: "{{ item.from_port | default('') }}"
   to_port: "{{ item.to_port | default('') }}"
   protocol: "{{ item.protocol | default('any') }}"
   route: "{{ item.route | default(omit) }}"
   log: "{{ item.log | default(false) }}"
   comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ ufw_rules }}"
  notify: reload ufw
- name: "Allow access from RFC1918 networks to this host"
  ufw: rule=allow src="{{ item }}"
  with_items:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
- name: "Enable Logging & restart ufw"
  ufw: logging=on
  notify: reload ufw
- name: "View Ufw rules"
  command: ufw status
  register: out
- debug: var=out.stdout_lines
- name: "Install netfilter-persistent && iptables-persistent packages"
  package:
   name: "{{item}}"
   state: present
  with_items:
  - iptables-persistent
  - netfilter-persistent
  when: ansible_os_family == "Ubuntu"
- name: "save iptables"
  command: iptables-save
- name: "Install the fail2ban package"
  package:
   name: fail2ban
   state: latest
- name: "Override some basic fail2ban configurations"
  copy:
   src: jail.local  
   dest: /etc/fail2ban/jail.local
   owner: root
   group: root
   mode: 0644
- name: "Enable firewall"
  ufw: state=enabled
  notify: Restart ssh
- name: "Change ssh port to user defined"
  lineinfile: 
   dest=/etc/ssh/sshd_config
   regexp="^Port\s"
   line="Port {{ ubuntu_login_ssh_port }}"
   state=present
  notify: Restart ssh
- name: "Disallow root SSH access"
  lineinfile: 
   dest=/etc/ssh/sshd_config
   regexp="^PermitRootLogin"
   line="PermitRootLogin no"
   state=present
  notify: Restart ssh
