prometheus_port_default: "{{ lookup('env','PROMETHEUS_PORT') }}"
prometheus_nodes_port: "{{ lookup('env','PROMETHEUS_NODES_PORT') }}"
node_exporter_port: "{{ lookup('env','NODE_EXPORTER_PORT') }}"
grafana_server_port: "{{ lookup('env','GRAFANA_PORT') }}"
ubuntu_login_ssh_port: "{{ lookup('env','SERVICE_SSH_PORT') }}"
core_node_address: "{{ lookup('env','CORE_ADDR') }}"
relay1_node_address: "{{ lookup('env','RELAY1_ADDR') }}"
relay2_node_address: "{{ lookup('env','RELAY2_ADDR') }}"
relay3_node_address: "{{ lookup('env','RELAY3_ADDR') }}"
home_dir: "{{ lookup('env','HOME_DIR') }}"
ufw_rules:
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: "{{ ubuntu_login_ssh_port }}"
   protocol: tcp
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: "{{ prometheus_port_default }}"
   protocol: tcp
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: "{{ grafana_server_port }}"
   protocol: tcp
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: 5432
   protocol: tcp
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: 443
   protocol: tcp
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: 80
   protocol: tcp
