node_alias: block-producer
node_port: "{{ lookup('env','CORE_PORT') }}"
relay1_node_address: "{{ lookup('env','RELAY1_ADDR') }}"
service_node_address: "{{ lookup('env','SERVICE_NODE_ADDR') }}"
prometheus_port_default: "{{ lookup('env','PROMETHEUS_NODES_PORT') }}"
ubuntu_login_ssh_port: "{{ lookup('env','SSH_PORT') }}"
node_exporter_port: "{{ lookup('env','NODE_EXPORTER_PORT') }}"
cardano_tag_version: "{{ lookup('env','CARDANO_TAG_VERSION') }}"
cardano_node_version: "{{ lookup('env','CARDANO_NODE_VERSION') }}"
home_dir: "{{ lookup('env','HOME_DIR') }}"
ufw_rules:
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: "{{ ubuntu_login_ssh_port }}"
   protocol: tcp
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: "{{ node_port }}"
   from_ip: "{{ relay1_node_address }}"
   protocol: tcp
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: "{{ prometheus_port_default }}"
   from_ip: "{{ service_node_address }}"
   protocol: tcp
 - rule: allow
   interface: "{{ ansible_default_ipv4['interface'] }}"
   to_port: "{{ node_exporter_port }}"
   from_ip: "{{ service_node_address }}"
   protocol: tcp
