node_alias: block-producer
cardano_tag_version: "{{ lookup('env','CARDANO_TAG_VERSION') }}"
cardano_node_version: "{{ lookup('env','CARDANO_NODE_VERSION') }}"
home_dir: "{{ lookup('env','HOME_DIR') }}"
